export DOTFILES="$HOME/Git/dotfiles"

source $DOTFILES/zsh/alias.zsh
source $DOTFILES/zsh/bindkeys.zsh
source $DOTFILES/zsh/completion.zsh
source $DOTFILES/zsh/functions.zsh
source $DOTFILES/zsh/history.zsh
source $DOTFILES/zsh/plugins.zsh

[ -f ~/.fzf.zsh  ] && source ~/.fzf.zsh
eval "$(rbenv init -)"

ulimit -S -n 2048

export EDITOR=nvim
export VISUAL=nvim
export DISABLE_SPRING=1

export HOMEBREW_CASK_OPTS="--appdir=/Applications"
export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export N_PREFIX="$HOME/n";

export PATH=":$N_PREFIX/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/Library/Android/sdk/platform-tools:$PATH"
export PATH="/Users/nddery/Library/Python/3.7/bin:$PATH"
